Table A2: Main alcohol related issues in the local area (%)

In [1]:
from gssutils import *

if is_interactive():
    scraper = Scraper(
        "https://www.justice-ni.gov.uk/publications/"
        "research-and-statistical-bulletin-82017-views-alcohol-and-drug-related-issues-findings-october-2016")
scraper

## Research and Statistical Bulletin 8/2017 ‘Views on Alcohol and Drug Related Issues: Findings from the October 2016 Northern Ireland Omnibus Survey’

### Distributions

1. Bulletin 8-3028 omnibus survey views on alcohol and drug related issues: Findings from October 2016 ([application/pdf](https://www.justice-ni.gov.uk/sites/default/files/publications/justice/oct-2016-omnibus-survey-drugs-alcohol-bulletin.pdf))
1. October 2016 alcohol and drugs findings data table ([MS Excel Spreadsheet](https://www.justice-ni.gov.uk/sites/default/files/publications/justice/ni-omnibus-survey-oct-2016-alcohol-drugs-tabular.xlsx))
1. Drugs and alcohol infographics 2016 ([application/pdf](https://www.justice-ni.gov.uk/sites/default/files/publications/justice/drugs-and-alcohol-infographics-2016.pdf))

In [2]:
if is_interactive():
    tabs = {tab.name: tab for tab in scraper.distribution(
        title='October 2016 alcohol and drugs findings data table').as_databaker()}
tabs.keys()

dict_keys(['Metadata', 'Index', 'Table A1', 'Table A2', 'Table A3', 'Table A4', 'Table A5', 'Table A6', 'Table A7', 'Table A8', 'Table A9', 'Table A10', 'Table A11', 'Table A12', 'Table A13', 'Table A14', 'Table A15', 'Table A16', 'Table A17', 'Table B1', 'Table B2', 'Table B3'])

https://www.justice-ni.gov.uk/sites/default/files/publications/justice/ni-omnibus-survey-oct-2016-alcohol-drugs-tabular.xlsx

In [3]:
tab = tabs['Table A2']

In [4]:
observations = tab.excel_ref('B5').expand(DOWN).expand(RIGHT).is_not_blank()

In [5]:
observations

{<E18 0.047>, <F17 0.07>, <F22 329.0>, <B20 0.0>, <D19 0.009>, <F12 0.05>, <F8 0.03>, <F15 0.045>, <C7 0.126>, <F16 0.054>, <B15 0.008>, <D20 0.003>, <D8 0.023>, <D22 388.0>, <E12 0.059>, <C13 0.034>, <C14 0.011>, <E20 0.0>, <F6 0.057>, <C18 0.008>, <B16 0.007>, <E16 0.063>, <E6 0.047>, <B12 0.015>, <C12 0.033>, <C16 0.015>, <F20 0.0>, <D6 0.23>, <D16 0.041>, <D13 0.079>, <F11 0.111>, <C17 0.021>, <F18 0.05>, <C6 0.187>, <F19 0.035>, <E7 0.134>, <B13 0.011>, <B6 0.099>, <E10 0.119>, <D9 0.104>, <C9 0.088>, <E13 0.101>, <E9 0.116>, <E22 369.0>, <B18 0.003>, <B19 0.0>, <F13 0.122>, <B5 0.591>, <D7 0.156>, <E19 0.006>, <E15 0.042>, <E8 0.03>, <D14 0.04>, <D10 0.133>, <E17 0.038>, <E5 0.041>, <B11 0.015>, <B17 0.007>, <C15 0.015>, <D5 0.029>, <D15 0.011>, <C11 0.019>, <B14 0.008>, <F9 0.104>, <F5 0.029>, <D11 0.039>, <D12 0.04>, <C22 405.0>, <C19 0.003>, <C5 0.066>, <B9 0.049>, <D18 0.017>, <C8 0.331>, <E11 0.078>, <C20 0.0>, <F10 0.097>, <C10 0.044>, <B7 0.091>, <E14 0.083>, <B10 0.021>, <F7 0.037>, <D17 0.046>, <B8 0.076>, <B22 415.0>, <F14 0.107>}

In [6]:
Alcoholissue = tab.excel_ref('B3').expand(RIGHT).is_not_blank()
Alcoholissue

{<B3 'Primary issue'>, <D3 'Tertiary issue'>, <E3 'Quaternary issue'>, <C3 'Secondary issue'>, <F3 'Quinary issue'>}

In [7]:
Alcoholrelatedissue = tab.excel_ref('A5').expand(DOWN).is_not_blank()
Alcoholrelatedissue

{<A6 'Rowdy and drunken behaviour'>, <A5 'Underage drinking'>, <A18 'Indecent exposure/urinating in street'>, <A17 'Spiking of drinks'>, <A12 'Theft'>, <A11 'Personal safety'>, <A14 'General disturbance'>, <A13 'Vandalism'>, <A20 'Other'>, <A19 'Unwanted sexual contact'>, <A25 '1. Results exclude "don\'t know" and refusals.'>, <A8 'Drinking in public places'>, <A22 'Unweighted base'>, <A24 'Source: Northern Ireland Omnibus Survey, October 2016'>, <A7 'Drink-driving'>, <A10 'Underage sales of alcohol'>, <A15 'Joy riding'>, <A16 'Litter'>, <A9 'Alcohol use/abuse'>}

In [8]:
Dimensions = [
            HDim(Alcoholissue,'Alcohol issue',DIRECTLY,ABOVE),
            HDim(Alcoholrelatedissue,'Alcohol related issue',DIRECTLY,LEFT),
            HDimConst('Measure Type', 'Percentage'),
            HDimConst('Unit','People')
            ]

In [9]:
c1 = ConversionSegment(observations, Dimensions, processTIMEUNIT=True)
# savepreviewhtml(c1)

In [10]:
new_table = c1.topandas()
new_table

,OBS,Alcohol issue,Alcohol related issue,Measure Type,Unit
0,0.591,Primary issue,Underage drinking,Percentage,People
1,0.066,Secondary issue,Underage drinking,Percentage,People
2,0.029,Tertiary issue,Underage drinking,Percentage,People
3,0.041,Quaternary issue,Underage drinking,Percentage,People
4,0.029,Quinary issue,Underage drinking,Percentage,People
5,0.099,Primary issue,Rowdy and drunken behaviour,Percentage,People
6,0.187,Secondary issue,Rowdy and drunken behaviour,Percentage,People
7,0.230,Tertiary issue,Rowdy and drunken behaviour,Percentage,People
8,0.047,Quaternary issue,Rowdy and drunken behaviour,Percentage,People
9,0.057,Quinary issue,Rowdy and drunken behaviour,Percentage,People
10,0.091,Primary issue,Drink-driving,Percentage,People
11,0.126,Secondary issue,Drink-driving,Percentage,People
12,0.156,Tertiary issue,Drink-driving,Percentage,People
13,0.134,Quaternary issue,Drink-driving,Percentage,People
14,0.037,Quinary issue,Drink-driving,Percentage,People
15,0.076,Primary issue,Drinking in public places,Percentage,People
16,0.331,Secondary issue,Drinking in public places,Percentage,People
17,0.023,Tertiary issue,Drinking in public places,Percentage,People
18,0.030,Quaternary issue,Drinking in public places,Percentage,People
19,0.030,Quinary issue,Drinking in public places,Percentage,People
20,0.049,Primary issue,Alcohol use/abuse,Percentage,People
21,0.088,Secondary issue,Alcohol use/abuse,Percentage,People
22,0.104,Tertiary issue,Alcohol use/abuse,Percentage,People
23,0.116,Quaternary issue,Alcohol use/abuse,Percentage,People
24,0.104,Quinary issue,Alcohol use/abuse,Percentage,People
25,0.021,Primary issue,Underage sales of alcohol,Percentage,People
26,0.044,Secondary issue,Underage sales of alcohol,Percentage,People
27,0.133,Tertiary issue,Underage sales of alcohol,Percentage,People
28,0.119,Quaternary issue,Underage sales of alcohol,Percentage,People
29,0.097,Quinary issue,Underage sales of alcohol,Percentage,People
...,...,...,...,...,...
55,0.007,Primary issue,Litter,Percentage,People
56,0.015,Secondary issue,Litter,Percentage,People
57,0.041,Tertiary issue,Litter,Percentage,People
58,0.063,Quaternary issue,Litter,Percentage,People
59,0.054,Quinary issue,Litter,Percentage,People
60,0.007,Primary issue,Spiking of drinks,Percentage,People
61,0.021,Secondary issue,Spiking of drinks,Percentage,People
62,0.046,Tertiary issue,Spiking of drinks,Percentage,People
63,0.038,Quaternary issue,Spiking of drinks,Percentage,People
64,0.070,Quinary issue,Spiking of drinks,Percentage,People
65,0.003,Primary issue,Indecent exposure/urinating in street,Percentage,People
66,0.008,Secondary issue,Indecent exposure/urinating in street,Percentage,People
67,0.017,Tertiary issue,Indecent exposure/urinating in street,Percentage,People
68,0.047,Quaternary issue,Indecent exposure/urinating in street,Percentage,People
69,0.050,Quinary issue,Indecent exposure/urinating in street,Percentage,People
70,0.000,Primary issue,Unwanted sexual contact,Percentage,People
71,0.003,Secondary issue,Unwanted sexual contact,Percentage,People
72,0.009,Tertiary issue,Unwanted sexual contact,Percentage,People
73,0.006,Quaternary issue,Unwanted sexual contact,Percentage,People
74,0.035,Quinary issue,Unwanted sexual contact,Percentage,People
75,0.000,Primary issue,Other,Percentage,People
76,0.000,Secondary issue,Other,Percentage,People
77,0.003,Tertiary issue,Other,Percentage,People
78,0.000,Quaternary issue,Other,Percentage,People
79,0.000,Quinary issue,Other,Percentage,People
80,415.000,Primary issue,Unweighted base,Percentage,People
81,405.000,Secondary issue,Unweighted base,Percentage,People
82,388.000,Tertiary issue,Unweighted base,Percentage,People
83,369.000,Quaternary issue,Unweighted base,Percentage,People
84,329.000,Quinary issue,Unweighted base,Percentage,People

In [11]:
new_table.columns = ['Response' if x=='OBS' else x for x in new_table.columns]

In [12]:
new_table.dtypes

Response                 float64
Alcohol issue             object
Alcohol related issue     object
Measure Type              object
Unit                      object
dtype: object

In [13]:
new_table.tail(5)

    Response     Alcohol issue Alcohol related issue Measure Type    Unit
80     415.0     Primary issue       Unweighted base   Percentage  People
81     405.0   Secondary issue       Unweighted base   Percentage  People
82     388.0    Tertiary issue       Unweighted base   Percentage  People
83     369.0  Quaternary issue       Unweighted base   Percentage  People
84     329.0     Quinary issue       Unweighted base   Percentage  People

In [14]:
new_table.head()

   Response     Alcohol issue Alcohol related issue Measure Type    Unit
0     0.591     Primary issue     Underage drinking   Percentage  People
1     0.066   Secondary issue     Underage drinking   Percentage  People
2     0.029    Tertiary issue     Underage drinking   Percentage  People
3     0.041  Quaternary issue     Underage drinking   Percentage  People
4     0.029     Quinary issue     Underage drinking   Percentage  People

In [15]:
new_table['Response'] = pd.to_numeric(new_table['Response'], errors='coerce')

In [16]:
new_table['Response'] = new_table['Response'].apply(str)

In [17]:
def user_perc(x,y):
    
    if str(x) == 'Unweighted base':
        return 'Number'
    else:
        return y
    
new_table['Measure Type'] = new_table.apply(lambda row: user_perc(row['Alcohol related issue'],row['Measure Type']), axis = 1)

In [18]:
new_table = new_table[['Alcohol related issue','Alcohol issue','Measure Type','Response','Unit']]

In [19]:
new_table.head(5)

  Alcohol related issue     Alcohol issue Measure Type Response    Unit
0     Underage drinking     Primary issue   Percentage    0.591  People
1     Underage drinking   Secondary issue   Percentage    0.066  People
2     Underage drinking    Tertiary issue   Percentage    0.029  People
3     Underage drinking  Quaternary issue   Percentage    0.041  People
4     Underage drinking     Quinary issue   Percentage    0.029  People

In [20]:
from pathlib import Path
destinationFolder = Path('out')
destinationFolder.mkdir(exist_ok=True, parents=True)

new_table.to_csv(destinationFolder / ('taba2.csv'), index = False)